# Site settings
title: L'@nnexe
subtitle: EPN du Relais 59
email: epn@csrelais59.org
description: Espace Public Numérique du 12e arrondissement.
baseurl:  # the subpath of your site, e.g. /blog
url:  # the base hostname & protocol for your site
author:
street_address: 8 place Henri Frenay
city: Paris
state:
zip_code: 75012
country:
phone: 09 53 21 27 82

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/relais59
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# Sass building
sass:
    sass_dir: _sass

# Build settings
markdown: kramdown
